- name: "Installation de Bin9 sur les DNS"
  hosts: dns
  remote_user: root

  tasks:
  - name: "Update les fichers apt"
    ansible.builtin.apt:
      update_cache: yes

  - name : "Installation Bin9"
    ansible.builtin.package:
      name: bind9
      state: present

  - name: "Exec du shell"  
    ansible.builtin.shell: date +%s&
    register: timestamp


- name: "Reconfiguration des VM pour utiliser les DNS internes"
  hosts: all
  remote_user: root

  tasks:
  - name : "Importation set_dns"
    ansible.builtin.import_tasks:
      file: tasks/set_dns.yml